---
# - name: Add helm traefik repo
#   ansible.builtin.command: helm repo add traefik https://traefik.github.io/charts
#   environment:
#      KUBECONFIG: /etc/rancher/k3s/k3s.yaml

# - name: Update helm repo
#   ansible.builtin.command: helm repo update
#   environment:
#      KUBECONFIG: /etc/rancher/k3s/k3s.yaml

# - name: Install traefik
#   ansible.builtin.command: helm install traefik traefik/traefik
#   environment:
#      KUBECONFIG: /etc/rancher/k3s/k3s.yaml

- name: Copy <manifests>.yml
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: ~/
    owner: root
    group: root
    mode: u=rw,g=r,o=
  with_fileglob:
    - "{{ role_path }}/files/*.yml"

- name: Deploy pod
  ansible.builtin.shell: kubectl -f ~/$(basename {{ item }}) apply
  loop: "{{ lookup('fileglob', '{{ role_path }}/files/*.yml', wantlist=True) | sort }}"
