---

- name: Download get_helm.sh
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
    dest: ~/get_helm.sh
    mode: u=rwx,g=,o=

- name: Install helm from script
  ansible.builtin.command: sh ~/get_helm.sh
  args:
    creates: /usr/local/bin/helm
  register: output

- name: Print stdout
  ansible.builtin.debug:
    var: output.stdout_lines

- name: Print stdout
  ansible.builtin.debug:
    var: output.stderr_lines
