---
- name: Copy <manifest>.yml
  ansible.builtin.copy:
    src: "{{ role_path }}/files/wordpress.yml"
    dest: ~/wordpress.yml
    owner: root
    group: root
    mode: u=rw,g=r,o=

- name: Deploy pod
  ansible.builtin.command: kubectl -f ~/wordpress.yml apply
