---
# - name: Add helm longhorn repo
#   ansible.builtin.shell: source ~/.bashrc && helm repo add longhorn https://charts.longhorn.io
#   args:
#     executable: /bin/bash

# - name: Update helm repo
#   ansible.builtin.shell: source ~/.bashrc && helm repo update
#   args:
#     executable: /bin/bash

# - name: Create kubernetes longhorn namespace
#   ansible.builtin.shell: source ~/.bashrc && kubectl create namespace longhorn-system
#   args:
#     executable: /bin/bash

# - name: Install longhorn
#   ansible.builtin.shell: source ~/.bashrc && helm install longhorn longhorn/longhorn --namespace longhorn-system
#   args:
#     executable: /bin/bash

- name: Copy <manifests>.yml
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "~/"
    owner: root
    group: root
    mode: u=rw,g=r,o=
  with_fileglob:
    - "{{ role_path }}/files/*.yml"

- name: Deploy pod
  ansible.builtin.shell: "kubectl -f ~/$(basename {{ item }}) apply"
  loop: "{{ lookup('fileglob', '{{ role_path }}/files/*.yml', wantlist=True) | sort }}"
