---
# - name: Add helm longhorn repo
#   ansible.builtin.command: helm repo add longhorn https://charts.longhorn.io
#   environment:
#      KUBECONFIG: /etc/rancher/k3s/k3s.yaml

# - name: Update helm repo
#   ansible.builtin.command: helm repo update
#   environment:
#      KUBECONFIG: /etc/rancher/k3s/k3s.yaml

# - name: Create kubernetes longhorn namespace
#   ansible.builtin.command: kubectl create namespace longhorn-system

# - name: Install longhorn
#   ansible.builtin.command: helm install longhorn longhorn/longhorn --namespace longhorn-system
#   environment:
#      KUBECONFIG: /etc/rancher/k3s/k3s.yaml

- name: Copy <manifests>.yml
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: ~/
    owner: root
    group: root
    mode: u=rw,g=r,o=
  with_fileglob:
    - "{{ role_path }}/files/*.yml"

- name: Deploy pod
  ansible.builtin.shell: kubectl -f ~/$(basename {{ item }}) apply
  loop: "{{ lookup('fileglob', '{{ role_path }}/files/*.yml', wantlist=True) | sort }}"
