apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: in-cluster
    namespace: default
  project: default
  source:
    path: apps/
    repoURL: https://github.com/Entepotenz/k3s_experiments.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true