---
- name: Install unattended-upgrades package
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  with_items:
    - unattended-upgrades
  when: "item not in ansible_facts.packages"

- name: Start unattended-upgrades service
  ansible.builtin.service:
    name: unattended-upgrades
    state: started
    enabled: true

- name: Configure Allowed origins for automatic updates
  ansible.builtin.replace:
    path: /etc/apt/apt.conf.d/50unattended-upgrades
    # Remove comment from matching lines
    regexp: '^(\s*)\/\/(\s*)(.*origin.*)(.*codename.*distro_codename.*)(.*-{{ item }}.*)$'
    replace: '\1\2\3\4\5'
  loop:
    - 'security'
    - 'updates'
  notify: Restart unattended-upgrades service

- name: Enable automatic updates
  ansible.builtin.copy:
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    mode: u=rw,g=r,o=r
    owner: root
    group: root
    content: |
      APT::Periodic::Update-Package-Lists "7";
      APT::Periodic::Unattended-Upgrade "7";
      APT::Periodic::AutocleanInterval "7";
  notify: Restart unattended-upgrades service
