---
- name: Install packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  with_items:
    - vim
  when: "item not in ansible_facts.packages"

- name: Clone Vimrc Repository
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/amix/vimrc/master/vimrcs/basic.vim
    dest: "$HOME/.vim_runtime"
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: u=rw,g=r,o=r
  become_user: "{{ item }}"
  loop: "{{ system.vim_users }}"
  when: system.vim_users is defined
