---
- name: Install OpenSSH server
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  with_items:
    - openssh-server
  when: "item not in ansible_facts.packages"

- name: Enable auto start of ssh server
  ansible.builtin.service:
    name: sshd
    state: started
    enabled: true

- name: Configure values
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?\s*{{ item.key }}\s'
    line: "{{ item.key }} {{ item.value }}"
    state: present
    validate: "sshd -t -f %s"
  with_dict:
    - Protocol: "2"
    - StrictModes: "yes"
    - Port: "{{ system.ssh_port }}"
    - PermitRootLogin: "prohibit-password"
    - PubkeyAuthentication: "yes"
    - Ciphers: "chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr"
    - HostKeyAlgorithms: "ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,rsa-sha2-512,rsa-sha2-256"
    - KexAlgorithms: "curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521"
