# Ein Secret mit Benutzername und Kennwort für die Datenbank im Backend.
apiVersion: v1
kind: Secret
metadata:
  name: secret-wp-db
  namespace: backend
type: Opaque
stringData:
  rootPassword: secureRootPassword
  username: wp-user
  password: wp-password
---
# Ein weiteres Secret mit Benutzername und Kennwort für das Frontend.
# Wegen der Trennung in Namespaces ist das hier doppelt.
apiVersion: v1
kind: Secret
metadata:
  name: secret-wp-fe
  namespace: frontend
type: Opaque
stringData:
  username: wp-user
  password: wp-password
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-wp-fe
  namespace: frontend
data:
  WORDPRESS_DB_HOST: wp-database.backend
  WORDPRESS_DB_NAME: wp
