---

- name: Run k3s installation script
  ansible.builtin.shell: curl -sfL https://get.k3s.io | sh -s - server --cluster-init
  register: output

- ansible.builtin.debug: var=output.stdout_lines

- ansible.builtin.debug: var=output.stderr_lines

- name: Wait for server_token
  ansible.builtin.wait_for:
    path: "/var/lib/rancher/k3s/server/token"

- name: Read server_token from master
  ansible.builtin.slurp:
    path: "/var/lib/rancher/k3s/server/token"
  register: server_token

- name: Store Master server_token
  ansible.builtin.set_fact:
    server_token: "{{ server_token.content | b64decode | regex_replace('\n', '') }}"

- name: Wait for node_token
  ansible.builtin.wait_for:
    path: "/var/lib/rancher/k3s/server/node-token"

- name: Read node_token from master
  ansible.builtin.slurp:
    path: "/var/lib/rancher/k3s/server/node-token"
  register: node_token

- name: Store Master node_token
  ansible.builtin.set_fact:
    node_token: "{{ node_token.content | b64decode | regex_replace('\n', '') }}"

- name: Store k3s control plane URL
  ansible.builtin.set_fact:
    control_plane_url: "https://{{ ansible_hostname }}:6443"
