---

- name: Run k3s installation script
  ansible.builtin.shell: curl -sfL https://get.k3s.io | K3S_URL={{ hostvars[groups['master'][0]]['control_plane_url'] | quote }} K3S_TOKEN={{ hostvars[groups['master'][0]]['node_token'] | quote }} sh -
  register: output

- ansible.builtin.debug: var=output.stdout_lines

- ansible.builtin.debug: var=output.stderr_lines

- name: Populate service facts
  ansible.builtin.service_facts:

- name: Print service facts
  ansible.builtin.debug:
    var: ansible_facts.services['k3s-agent.service']
