---
- name: Uninstall k3s everywhere
  hosts: all
  become: true
  roles:
    - reset

- name: Install k3s on first master to setup control plane
  hosts: master[0]
  become: true
  roles:
    - general-system
    - configuration
    - install
    - install-helm
    - install-argocd

- name: Install k3s on other masters and connect them to control plane
  hosts: master[1:]
  become: true
  roles:
    - general-system
    - configuration
    - install-with-server-token

- name: Add k3s nodes
  hosts: node
  become: true
  roles:
    - general-system
    - install-with-node-token

# - name: Apply First pod - part1
#   hosts: master[0]
#   become: true
#   roles:
#     - 01-sample-service
#     # remove pod with those commands:
#     # kubectl delete pod my-first-nginx
#     # kubectl delete service my-service

# - name: Apply Second pod - part2
#   hosts: master[0]
#   become: true
#   roles:
#     - 02-sample-service
#     # show where the pod is running:
#     # kubectl get pods -o wide
#     # test loadbalancer by doing curl to the nodes
#     # curl XXXX:30000
#     # image austauschen und damit rolling update test ("containous/whoami:latest" durch "nginx:latest" ersetzen und vice versa):
#     # kubectl get pods -w
#     # remove pod with those commands:
#     # kubectl delete deployment my-first-nginx-deployment
#     # kubectl delete service my-service

# - name: Apply Third pod - part3
#   hosts: master[0]
#   become: true
#   roles:
#     - 03-sample-service-wordpress
#     # setup helm
#     # helm ls
#     # helm repo add traefik https://traefik.github.io/charts
#     # helm repo update
#     # helm install traefik traefik/traefik
#     # helm upgrade traefik traefik/traefik
#     # kubectl delete -f ~/wordpress.yml

# - name: Apply Fourth pod - part4
#   hosts: master[0]
#   become: true
#   roles:
#     - 04-sample-service-wordpress
#     # setup helm
#     # helm ls
#     # helm repo add traefik https://traefik.github.io/charts
#     # helm repo update
#     # helm install traefik traefik/traefik
#     # helm upgrade traefik traefik/traefik
#     # kubectl delete -f ~/wordpress.yml

# - name: Apply Fifth pod - part5
#   hosts: master[0]
#   become: true
#   roles:
#     - 05-sample-service-wordpress-network-policies

# - name: Apply sixth pod - part6
#   hosts: master[0]
#   become: true
#   roles:
#     - 06-sample-service-wordpress-longhorn
#     # check if all systems are ready for longhorn
#     # kubectl get pods -n longhorn-system
#     # delete
#     # kubectl -f ~/nginx-with-longhorn.yml delete
#     # uninstall longhorn:
#     # kubectl -n longhorn-system patch -p '{"value": "true"}' --type=merge lhs deleting-confirmation-flag
#     # helm uninstall longhorn -n longhorn-system
#     # kubectl delete namespace longhorn-system
