---
- name: Restart fail2ban
  ansible.builtin.service:
    name: fail2ban
    state: restarted

- name: Restart SSH daemon
  ansible.builtin.service:
    name: sshd
    state: restarted

- name: Restart unattended-upgrades service
  ansible.builtin.service:
    name: unattended-upgrades
    state: restarted
